#pragma kernel CSMain

#include "UnityCG.cginc" 

uniform sampler2D _Tex1;
uniform sampler2D _Tex2;
uniform float _Lerp;
uniform float2 _Dimensions;
RWTexture2D<float4> _Tex3;

[numthreads(4, 4, 1)]
void CSMain(uint2 id : SV_DispatchThreadID)
{
	float4 uv = float4((float(id.x) + 0.5) * _Dimensions.x, (float(id.y) + 0.5) * _Dimensions.y, 0.0, 0.0);
	float4 samp1 = tex2Dlod(_Tex1, uv);
	float4 samp2 = tex2Dlod(_Tex2, uv);
	_Tex3[id.xy] = lerp(samp1, samp2, _Lerp);
}
